# Generated by Django 4.1 on 2022-10-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfile',
            name='otp',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
