# Generated by Django 4.1.2 on 2022-10-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_prfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
